In [2]:
import dash
# Code from: https://github.com/plotly/dash-labs/tree/main/docs/demos/multi_page_example1

from dash import Dash, dcc, html, Input, Output, callback
import plotly.express as px
import plotly.express as px
import pandas as pd

df1 = pd.read_csv("sp_irad_accident.csv")

df1['Month'] = pd.to_datetime(df1['insert_date'])
df1['Month'] = df1['Month'].dt.strftime('%m')
df1['Crashes']=1

In [10]:
df = df1.filter(["crash_type", "Month","Crashes","year",'state','total_dead'], axis=1)
df= df.groupby(['crash_type','Month','year','state','total_dead']).sum().reset_index()
df

      crash_type Month  year  state  total_dead  Crashes
0              1    01  2021      2           1        8
1              1    01  2021      2           2        5
2              1    01  2021      2           3       10
3              1    01  2021      2           4        8
4              1    01  2021      2           5        7
...          ...   ...   ...    ...         ...      ...
5773           5    12  2021     36           1        4
5774           5    12  2021     36           2        1
5775           5    12  2021     36           3        3
5776           5    12  2021     36           4        2
5777           5    12  2021     36           5        2

[5778 rows x 6 columns]